#!/bin/sh
# periodically print date and load average to the bar

xwrite() {
	file="$1"; shift
	echo -n "$@" | wmiir write "$file"
}

wmiir remove /bar/status 2>/dev/null && sleep 2
wmiir create /bar/status
xwrite /bar/status/colors $WMII_NORMCOLORS

contents () {
    if [ -x "$(which tunes)" -a "$(tunes query | sed -e '/\(playing\|paused\)/!d')" ]; then 
        # Need to sanitize the output, too; Sigur Ros made that
        # obvious enough...
        PLAYING="$(tunes query | sed -e '1!d' -e 's/[^a-zA-Z ?.\/\\_+-]/_/g')"
    fi
    [ "${PLAYING}" ] && CONTENTS="${CONTENTS}[MPD: ${PLAYING}]"
    UPTIME="$(uptime | sed -e 's/.*up //' -e 's/, [0-9 ]\+ users.*//')"
    CONTENTS="${CONTENTS}[UP: ${UPTIME}]"
    CONTENTS="${CONTENTS}[$HOSTNAME]"
    CONTENTS="${CONTENTS}[$(date)]"
    COUNTER=$((COUNTER + 1))
    echo ${CONTENTS}
}

COUNTER=0
while xwrite /bar/status/data $(contents)
do
    sleep 2
done
