#!/bin/sh
# configure wmii

xwrite() {
	file="$1"; shift
	echo -n "$@" | wmiir write "$file"
}

proglist() {
	ls -lL "$@" 2>/dev/null | awk 'NF>2 && $1 ~ /^[^d].*x/ {print $NF}' | sort -u
}

cycleWs() {
    # Fails when view names have spaces in them. Don't use views that
    # have spaces in their names. Will also ignore views with leading
    # spaces in their names.
    case "X$1" in
        Xprev)
            REVERSE=1;;
        Xnext)
            REVERSE='';;
    esac
    WSES=$(wmiir read /tags)
    [ "${REVERSE}" ] && WSES=$(echo ${WSES} | sed -e 's/ /\n/g' | sort -rn)
    WSCUR=$(wmiir read /view/sel/sel/tags)

    # Double the WS list so that we can loop around, if needed.
    WSES="${WSES}
    ${WSES}"

    NEXTONE=''
    for WS in ${WSES}; do 
        if [ "${WS}" = "${WSCUR}" ]; then
            NEXTONE=1
        elif [ "${NEXTONE}" ]; then
            NEXTWS="${WS}"
            break
        fi
    done
    echo -n "view ${NEXTWS}" | wmiir write /ctl
}

MODKEY=Mod1
UP=k
DOWN=j
LEFT=h
RIGHT=l

WMII_FONT='-windows-proggysquare-medium-*-*-*-*-*-96-96-*-*-*-*'
#WMII_FONT='fixed'
WMII_SELCOLORS='#ffffff #285577 #4c7899'
WMII_NORMCOLORS='#222222 #eeeeee #666666'
# dark background
#WMII_NORMCOLORS='#e0e0e0 #0a0a0a #202020'

export WMII_FONT WMII_NORMCOLORS WMII_SELCOLORS

# give wmiiwm a chance to start
while :
do
	echo Start wmiirc | wmiir write /event >/dev/null 2>&1 && break
	sleep 1
done

# WM CONFIGURATION
xwrite /def/border 2
xwrite /def/font $WMII_FONT
xwrite /def/selcolors $WMII_SELCOLORS
xwrite /def/normcolors $WMII_NORMCOLORS
xwrite /def/colmode default
xwrite /def/colwidth 0

# TAGGING RULES
wmiir write /def/rules <<EOF
/XMMS.*/ -> ~
/Gimp.*/ -> ~
/MPlayer.*/ -> ~
/.*/ -> !
/.*/ -> 1
EOF

# MISC
xsetroot -solid '#333333'
status &
PROGS_FILE=/tmp/.wmiimenu.$USER.progs
proglist `echo "$PATH" | tr : ' '` >$PROGS_FILE &

# SHORTCUTS
xwrite /def/grabmod $MODKEY
wmiir write /def/keys <<EOF
$MODKEY-$LEFT
$MODKEY-$RIGHT
$MODKEY-$DOWN
$MODKEY-$UP
$MODKEY-space
$MODKEY-d
$MODKEY-f
$MODKEY-s
$MODKEY-m
$MODKEY-a
$MODKEY-p
$MODKEY-t
$MODKEY-0
$MODKEY-1
$MODKEY-2
$MODKEY-3
$MODKEY-4
$MODKEY-5
$MODKEY-6
$MODKEY-7
$MODKEY-8
$MODKEY-9
$MODKEY-Return
$MODKEY-Shift-$LEFT
$MODKEY-Shift-$RIGHT
$MODKEY-Shift-$UP
$MODKEY-Shift-$DOWN
$MODKEY-Shift-space
$MODKEY-Shift-c
$MODKEY-Shift-t
$MODKEY-Shift-0
$MODKEY-Shift-1
$MODKEY-Shift-2
$MODKEY-Shift-3
$MODKEY-Shift-4
$MODKEY-Shift-5
$MODKEY-Shift-6
$MODKEY-Shift-7
$MODKEY-Shift-8
$MODKEY-Shift-9
$MODKEY-Control-$LEFT
$MODKEY-Control-$RIGHT
$MODKEY-Control-$DOWN
$MODKEY-Control-$UP
# Personal Additions
$MODKEY-comma
$MODKEY-period
$MODKEY-c
$MODKEY-Shift-l
$MODKEY-Shift-k
F1
F2
f2
F3
F4
F5
$MODKEY-F5
F6
$MODKEY-F6
F7
$MODKEY-F7
F8
F9
F10
F11
F12
EOF

# EVENT LOOP
wmiir read /event 2>/dev/null |
while read event
do
	set -- $event
	type="$1"; shift
	case "$type" in
	Start)
		if test wmiirc = "$1"
		then
			exit
		fi;;
	BarClick)
		xwrite /ctl view ''"$1"'';;
	Key)
		case "$1" in
		$MODKEY-$LEFT)
			xwrite /view/ctl select prev;;
		$MODKEY-$RIGHT)
			xwrite /view/ctl select next;;
		$MODKEY-$DOWN)
			xwrite /view/sel/ctl select next;;
		$MODKEY-$UP)
			xwrite /view/sel/ctl select prev;;
		$MODKEY-space)
			xwrite /view/ctl select toggle;;
		$MODKEY-d)
			xwrite /view/sel/mode default;;
		$MODKEY-s)
			xwrite /view/sel/mode stack;;
		$MODKEY-m)
			xwrite /view/sel/mode max;;
		$MODKEY-f)
			xwrite /view/0/sel/geom 0 0 east south;;
		$MODKEY-a)
			PATH=$HOME/.wmii-3:/usr/local/etc/wmii-3:$PATH `proglist /usr/local/etc/wmii-3 $HOME/.wmii-3 | wmiimenu` &;;
		$MODKEY-p)
			`wmiimenu <$PROGS_FILE` &;;
		$MODKEY-t)
			xwrite /ctl view "`wmiir read /tags | wmiimenu`" &;;
		$MODKEY-[0-9])
			xwrite /ctl view `echo $1 | sed 's/.*-//'`;;
		$MODKEY-Return)
			$HOME/bin/term &;;
		$MODKEY-Shift-$LEFT)
			xwrite /view/sel/sel/ctl sendto prev;;
		$MODKEY-Shift-$RIGHT)
			xwrite /view/sel/sel/ctl sendto next;;
		$MODKEY-Shift-$DOWN)
			xwrite /view/sel/sel/ctl swap down;;
		$MODKEY-Shift-$UP)
			xwrite /view/sel/sel/ctl swap up;;
		$MODKEY-Shift-space)
			xwrite /view/sel/sel/ctl sendto toggle;;
		$MODKEY-Shift-c)
			xwrite /view/sel/sel/ctl kill;;
		$MODKEY-Shift-t)
			xwrite /view/sel/sel/tags ''"`wmiir read /tags | wmiimenu`"'' &;;
		$MODKEY-Shift-[0-9])
			xwrite /view/sel/sel/tags `echo $1 | sed 's/.*-//'`;;
		$MODKEY-Control-$LEFT)
			xwrite /view/sel/sel/ctl swap prev;;
		$MODKEY-Control-$RIGHT)
			xwrite /view/sel/sel/ctl swap next;;
		$MODKEY-Control-$DOWN)
			xwrite /view/sel/sel/ctl swap down;;
		$MODKEY-Control-$UP)
			xwrite /view/sel/sel/ctl swap up;;
                # Personal additions
                $MODKEY-comma)
                        # Jump to previous view
                        cycleWs prev;;
                $MODKEY-period)
                        # Jump to next view
                        cycleWs next;;
                $MODKEY-c)
                        # Kill a client.
			xwrite /view/sel/sel/ctl kill;;
                $MODKEY-Shift-l)
                        $HOME/bin/term &;;
                F2)
                        $HOME/bin/term &;;
                F4)
                        $HOME/bin/browser &;;
                F5)
                        $HOME/bin/tunes &;;
                $MODKEY-F5)
                        $HOME/bin/tunes stop &;;
                F6)
                        $HOME/bin/tunes volume -8 &;;
                $MODKEY-F6)
                        $HOME/bin/tunes prev &;;
                F7)
                        $HOME/bin/tunes volume +8 &;;
                $MODKEY-F7)
                        $HOME/bin/tunes next &;;
                F8)
                        $HOME/bin/tunes slide &;;
                F10)
                        $HOME/bin/lock &;;
                F11)
                        wmiirc &;;
                F12)
                        quit &;;
                esac
	esac
done
