# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind.enablesound", false);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateDate", 1140209896);
user_pref("browser.download.defaultFolder", "/home/will");
user_pref("browser.download.manager.retention", 0);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.link.open_external", 3);
user_pref("browser.preferences.lastpanel", 4);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.mstone", "rv:1.7.12");
user_pref("browser.tabs.autoHide", false);
user_pref("browser.tabs.loadBookmarksInBackground", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("extensions.disabledObsolete", true);
user_pref("extensions.lastAppVersion", "1.0");
user_pref("extensions.update.lastUpdateDate", 1140209896);
user_pref("general.open_location.last_url", "http://library.wisc.edu/");
user_pref("general.open_location.last_window_choice", 0);
user_pref("general.smoothScroll", true);
user_pref("intl.charsetmenu.browser.cache", "us-ascii, windows-1252, UTF-8, ISO-8859-1");
user_pref("keyconfig.main.addBookmarkAsKb", "shift][B][");
user_pref("keyconfig.main.f4kc_NextTab", "][.][");
user_pref("keyconfig.main.f4kc_PrevTab", "][,][");
user_pref("keyconfig.main.focusURLBar", "shift][O][");
user_pref("keyconfig.main.focusURLBar2", "control][O][");
user_pref("keyconfig.main.goBackKb", "][Y][");
user_pref("keyconfig.main.goForwardKb", "][U][");
user_pref("keyconfig.main.goHome", "][A][");
user_pref("keyconfig.main.key_find", "][/][");
user_pref("keyconfig.main.key_findAgain", "][N][");
user_pref("keyconfig.main.key_findPrevious", "shift][N][");
user_pref("keyconfig.main.key_fullScreen", "][F][");
user_pref("keyconfig.main.key_gotoHistory", "shift][H][");
user_pref("keyconfig.main.key_openDownloads", "][D][");
user_pref("keyconfig.main.key_reload", "][R][");
user_pref("keyconfig.main.key_search2", "][O][");
user_pref("keyconfig.main.key_viewInfo", "][I][");
user_pref("keyconfig.main.key_viewSource", "][S][");
user_pref("keyconfig.main.viewBookmarksSidebarKb", "][B][");
user_pref("keyconfig.main.xxx_key36_cmd_findAgain", "][N][");
user_pref("keyconfig.main.xxx_key37_cmd_findPrevious", "shift][N][");
user_pref("keyconfig.main.xxx_key_PageUp", "control][U][][goDoCommand('cmd_scrollPageUp');");
user_pref("keyconfig.main.xxx_key_ScrollBottom", "shift][G][][goDoCommand('cmd_scrollBottom');");
user_pref("keyconfig.main.xxx_key_ScrollLeft", "][H][][goDoCommand('cmd_scrollLeft');");
user_pref("keyconfig.main.xxx_key_ScrollLineDown", "][J][][goDoCommand('cmd_scrollLineDown');");
user_pref("keyconfig.main.xxx_key_ScrollLineUp", "][K][][goDoCommand('cmd_scrollLineUp');");
user_pref("keyconfig.main.xxx_key_ScrollPageDown", "control][F][][goDoCommand('cmd_scrollPageDown');");
user_pref("keyconfig.main.xxx_key_ScrollRight", "][L][][goDoCommand('cmd_scrollRight');");
user_pref("keyconfig.main.xxx_key_ScrollTop", "][G][][goDoCommand('cmd_scrollTop');");
user_pref("keyconfig.main.xxx_key_findTypeLinks", "][;][][goDoCommand('cmd_findTypeLinks');");
user_pref("keyconfig.version", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("security.OCSP.URL", "");
user_pref("security.OCSP.signingCA", "Builtin Object Token:IPS CLASE1 root");
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_submit_insecure", false);
user_pref("signon.rememberSignons", false);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
