#!/bin/sh

set -eu

export CGO_ENABLED=0
mkdir -p /build/go

pkg=./...
go get -d -v $pkg
exec go install -v -a \
	-ldflags '-d -s -w -extldflags "-static"' \
	-tags netgo \
	-installsuffix netgo \
	-pkgdir /build/go \
	$pkg

