# This file is generated by cmd/3p.


load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


def repo():

    http_archive(
        name = "vim_airline",
        sha256 = "64fbf3c9535195dcd3a739e5241391c0ab3b563e94dfd3e7a6877149ec0f55c9",
        strip_prefix = "vim-airline-c7fb175d3565159699885653767214a6aa583ea4",
        urls = [
            "https://github.com/vim-airline/vim-airline/archive/c7fb175d3565159699885653767214a6aa583ea4.tar.gz",
	],
    )

