#!/bin/sh

pkgs="\
	vis \
	git \
	make \
	python3 \
	docker \
	curl \
	file \
	fish \
	"
docs=$(printf "%s-doc " $pkgs)
allpkgs="$pkgs \
	$docs \
	man \
	outils-signify \
	outils-doc \
	su-exec \
	git-perl \
	fish-tools \
	mdocml-apropos \
	ncurses \
	"

apk --no-cache add $allpkgs

ln -s $(which python3) /usr/bin/python
ln -s $(which pydoc3) /usr/bin/pydoc

make

