#!/bin/sh

set -ex

pkgs="\
	git \
	make \
	python3 \
	docker \
	curl \
	file \
	fish \
	tmux \
	"
docs=$(printf "%s-doc " $pkgs)
allpkgs="$pkgs \
	$docs \
	vis \
	man \
	outils-signify \
	outils-doc \
	su-exec \
	git-perl \
	fish-tools \
	mdocml-apropos \
	ncurses \
	"

apk --no-cache add $allpkgs

ln -fs /usr/bin/vis /usr/bin/vis-editor

ln -fs /usr/bin/python3 /usr/bin/python
ln -fs /usr/bin/pydoc3 /usr/bin/pydoc

export GUP_XTRACE=1
export GUP_VERBOSE=1
make

