#!/bin/sh

addgroup -S me && adduser -u $USER_ID -S -g me me
chown -R me:me /home/me

case "$@"x in
	x) while :; do sleep 1d; done;;
	rootx) exec /bin/ash -l;;
	mex) exec su-exec me /bin/ash -l;;
	*) exec su-exec me "$@";;
esac
