#!/bin/sh

useradd -MUu $USER_ID -d $HOME $USER
chown -R $USER:$USER $HOME

export PATH=$HOME/bin:$PATH

case "$@"x in
	x) while :; do sleep 1d; done;;
	rootx) exec /bin/sh -l;;
	$USERx) exec su-exec $USER /bin/sh -l;;
	*) exec su-exec $USER "$@";;
esac
