(require 'delight)
(delight '((golden-ratio-mode nil "golden-ratio")
           (visual-line-mode nil "simple")
           (magit-auto-revert-mode "" "magit")
           (org-indent-mode "" "org-indent")
           (auto-fill-mode "" "Fill")
           (flyspell-mode nil "flyspell")))
