#!/bin/sh

pkgs="\
	vis \
	git \
	make \
	python3 \
	docker \
	curl \
	file \
	"
docs=$(printf "%s-doc " $pkgs)
allpkgs=$pkgs \
	$docs \
	man \
	outils-signify \
	outils-doc

apk --no-cache add $allpkgs

ln -s $(which python3) /usr/bin/python
ln -s $(which pydoc3) /usr/bin/pydoc

addgroup -S me && adduser -S -g me me 
chown -R me:me .

make
