#!/bin/sh

apk --no-cache add \
	vis \
	vis-doc \
	outils-signify \
	git \
	git-doc \
	make \
	make-doc \
	man \
	python3 \
	python3-doc \
	docker \
	docker-doc \
	curl \
	curl-doc

ln -s $(which python3) /usr/bin/python
ln -s $(which pydoc3) /usr/bin/pydoc

addgroup -S me && adduser -S -g me me 
chown -R me:me .

make
