name: bot
description: "Be a bot"
inputs:
  bot-id:
    description: "Bot ID"
    required: true
  bot-key:
    description: "Bot private key"
    required: true
outputs:
  token:
    description: "An authentication token"
runs:
  using: "docker"
  image: docker://ghcr.io/whilp/bot:latest
  env:
    BOT_ID: ${{ inputs.bot-id }}
    BOT_KEY: ${{ inputs.bot-key }}
