#!/usr/bin/env bash

set -euo pipefail

defaults write NSGlobalDomain com.apple.springing.enabled -bool true
defaults write NSGlobalDomain com.apple.springing.delay -float 0.5

echo "spring loading enabled with 0.5s delay"
