#!/usr/bin/env lua

local posix = require('posix')
local unistd = require('posix.unistd')
local wait = require('posix.sys.wait')

local handle = posix.popen({"/bin/sh", "-c", "defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false"}, "r")
local output = unistd.read(handle.fd, 65536) or ""
local _, reason, exit_code = wait.wait(handle.pids[1])
unistd.close(handle.fd)

if reason ~= "exited" or exit_code ~= 0 then
  io.stderr:write("tiling-disable: failed to disable window tiling\n")
  os.exit(exit_code or 1)
end
