#!/bin/bash

source ~/.config/setup/env

(
  cd "$DST"
  if [ ! -d ./ai ]; then
    git clone ${REMOTE%/*}/ai ./ai
  else
    (
      cd ./ai
      git fetch
    )
  fi

  claude plugin marketplace add ./ai
)
