#!/bin/bash

source "$(dirname "$0")/env"

if [ "${CODESPACES}" = "true" ]; then
  shimlink update claude &
fi

config="$DST/.claude.json"
[ -r "$config" ] && exit 0

if [ -n "${CLAUDE_CREDENTIALS}" ]; then
  echo "${CLAUDE_CREDENTIALS}" >"$DST/.claude/.credentials.json"
fi

settings='{
  "numStartups": 1,
  "installMethod": "unknown",
  "autoUpdates": false,
  "theme": "dark-daltonized",
  "hasCompletedOnboarding": true,
  "bypassPermissionsModeAccepted": true
}'
echo "$settings" >"$config"

wait
