#!/bin/bash

[ "$CODESPACES" != "true" ] && exit 0

source "$(dirname "$0")/env"

creation_log="/workspaces/.codespaces/.persistedshare/creation.log"
setup_log="$DST/setup.log"

if [ -f "$creation_log" ]; then
  ln -sf "$creation_log" "$setup_log"
fi
