#!/bin/bash

source "$(dirname "$0")/env"

extras=${REMOTE%/*}/extras
cd "$DST"
if [ ! -d extras ]; then
  if git clone "$extras" extras 2>/dev/null; then
    cd extras
    [ -x ./setup.sh ] && ./setup.sh
  fi
else
  cd ./extras
  git fetch
  [ -x ./setup.sh ] && ./setup.sh
fi
