#!/bin/bash

source "$(dirname "$0")/env"

shimlink update luajit
shimlink update ast-grep &
shimlink update biome &
# See .config/setup/claude
# shimlink update claude &
shimlink update comrak &
shimlink update delta &
shimlink update duckdb &
shimlink update gh &
shimlink update marksman &
shimlink update nvim &
shimlink update rg &
shimlink update ruff &
shimlink update shfmt &
shimlink update sqruff &
shimlink update stylua &
shimlink update superhtml &
shimlink update tree-sitter &
shimlink update uv &
wait
