#!/usr/bin/env python

from itertools import takewhile

message = []
from_hdr = ''
subject = ''

def fmt_header(header, value=None):
    if not value:
        return header, ''

    header = header.lower()
    if header == "from":
        value = [x for x in value.split() if '@' in x][0]
        value = value.split('@', 1)[0].strip("\"'<>")
    elif header == "subject":
        value = ' '.join(value.split())

    return header, value

is_header = lambda line: len(line.split(':')) >= 2
split_header = lambda line: fmt_header(*line.split(':', 1))
get_headers = lambda stream: dict(split_header(x) for x in takewhile(is_header, stream))

main = lambda instream, outstream: outstream.write(
        "%(from)s: %(subject)s"[:135] % get_headers(instream) + '\n')

if __name__ == '__main__':
    import sys
    main(sys.stdin, sys.stdout)
