#!/usr/bin/env python

import sys

message = []
from_hdr = ''
subject = ''

for line in sys.stdin:
    # We've reached the payload.
    if not line:
        break

    try:
        header, value = line.split(':', 1)
    except ValueError:
        message.append(line)
        continue

    if header.lower() == 'from':
        from_hdr = value
    elif header.lower() == 'subject':
        subject = value
        value = ' from %s' % from_hdr.strip()

    message.append(':'.join((header, value)))

print ''.join(message)
print subject.strip()
