#!/bin/sh
# Runs actual/preferred term command.
# aterm -tr -sh 100 -bw 0 +sb
# aterm -rv -g 120x25 -bg green -tr -sh 60 -bw 0 +sb
# xterm $*
# FONT="-windows-pixelcarnage monospace-*-*-*-*-*-*-*-*-*-*-*-*"
# urxvt -ip -tint black +sb -rv -tn linux \
#     -fn "$FONT" $*
#urxvt $*
# mlterm --bright=100 --ls --bel=visual --bg=black --fg=white \
#     --sb=false --transbg=true --88591=true --noucsfont=true


ARGS=$*
ARGS="$(echo "${ARGS}" | sed -e "s/-T \([^ ]*\)/-T ${HOSTNAME}\[\1\]/")"
aterm -tr -name "${HOSTNAME}[LOCAL]" ${ARGS}
