#!/bin/sh

# Read each line of the message, looking for a X-Item-Link header.
# X-Item-Link: http://lwn.net/Articles/240638/rss
URL=
while read LINE; do
    URL=$(echo ${LINE} | sed -e '/^X-Item-Link: /!d; s/^X-Item-Link: //')
    if [ -n "${URL}" ]; then
        /usr/local/bin/elinks -session-ring 1 -remote "openURL('${URL}', new-tab)"
    fi
done
