name: analyze

on:
  schedule:
    - cron: "0 6 * * 6"

jobs:
  analyze:
    strategy:
      matrix:
        language:
          - javascript
          - python
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/analyze@v1
