name: build

on:
  push:
    branches-ignore:
      - master

jobs:
  all:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2.0.1
        with:
          python-version: "3.7"
      - name: debug
        run: command -v python && command -v python3 && command -v python3.7 && python --version && echo $PATH
      - name: bazel build
        run: ./tools/bazel build --config=ci //...
