name: build

on:
  push:
    branches-ignore:
      - master

jobs:
  all:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: debug
        run: command -v python && command -v python3 && command -v python3.7 && python --version
      - name: bazel build
        run: ./tools/bazel build --config=ci //...
