name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ github.sha }}

      - name: bazel build
        run: ./tools/bazel build --config=ci //...

  test:
    runs-on: ubuntu-18.04
    needs: build
    if: ${{! github.event.pull_request.merged}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ github.sha }}

      - name: bazel test
        run: ./tools/bazel test --config=ci //...

  next:
    runs-on: ubuntu-18.04
    needs: build
    if: ${{! github.event.pull_request.merged}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ github.sha }}

      - name: docker login
        run: echo "$DOCKER" | docker login --password-stdin --username whilp
        env:
          DOCKER: ${{ secrets.DOCKER }}

      - name: bazel run image/devcontainer:next
        run: ./tools/bazel run --config=ci image/devcontainer:next
