name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ github.sha }}

      - name: bazel build
        run: ./tools/bazel build //...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ github.sha }}

      - name: bazel test
        run: ./tools/bazel test //...
