name: CI

on: [push]

jobs:
  cache:
    runs-on: ubuntu-18.04
    steps:
      - id: key
        run: echo "::set-output name=key::$(/bin/date -u "+%Y%m%d%H")"
      - id: restore-key
        run: echo "::set-output name=restore-key::$(/bin/date -u "+%Y%m%d")"

  build:
    runs-on: ubuntu-18.04
    needs: cache
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ needs.cache.outputs.key }}
          restore-keys: ${{ needs.build.outputs.restore-key }}
      - name: bazel build
        run: ./tools/bazel build --config=ci //...

  test:
    runs-on: ubuntu-18.04
    needs: cache
    if: ${{! github.event.pull_request.merged}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ needs.cache.outputs.key }}
          restore-keys: ${{ needs.build.outputs.restore-key }}
      - name: bazel test
        run: ./tools/bazel test --config=ci //...

  push_devcontainer_next:
    runs-on: ubuntu-18.04
    needs: cache
    if: ${{! github.event.pull_request.merged}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ needs.cache.outputs.key }}
          restore-keys: ${{ needs.build.outputs.restore-key }}
      - name: docker login
        run: echo "$DOCKER_TOKEN" | docker login --password-stdin --username "$DOCKER_USER"
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
      - name: bazel run image/devcontainer:next
        run: ./tools/bazel run --config=ci image/devcontainer:next

  push_devcontainer_latest:
    runs-on: ubuntu-18.04
    needs: cache
    if: ${{ github.event.pull_request.merged}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ needs.cache.outputs.key }}
          restore-keys: ${{ needs.build.outputs.restore-key }}
      - name: docker login
        run: echo "$DOCKER_TOKEN" | docker login --password-stdin --username "$DOCKER_USER"
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
      - name: bazel run image/devcontainer:next
        run: ./tools/bazel run --config=ci image/devcontainer:latest

  push_buildifier_latest:
    runs-on: ubuntu-18.04
    needs: cache
    if: ${{ github.event.pull_request.merged}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ needs.cache.outputs.key }}
          restore-keys: ${{ needs.build.outputs.restore-key }}
      - name: docker login
        run: echo "$DOCKER_TOKEN" | docker login --password-stdin --username "$DOCKER_USER"
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
      - name: bazel run image/buildifier:latest
        run: ./tools/bazel run --config=ci image/buildifier:latest
