name: github

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - opened
      - reopened

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - name: gh
        uses: docker://ghcr.io/whilp/gh:latest@sha256:f15d4457264ac96d69e439a2372e2b3d6740bfda92d2a33a8cd2bfb8475db9f6
        env:
          CONTEXT: lint / github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_DEPENDENCIES: dependencies
          LABEL_FEAT: feat
          LABEL_FIX: fix
