name: github

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - opened
      - reopened

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - name: gh
        uses: docker://ghcr.io/whilp/gh:latest@sha256:65aed18b6d9ee82a2b56701513cc5287c71305e7022c80be948a1489cc670544
        env:
          CONTEXT: lint / github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_DEPENDENCIES: dependencies
          LABEL_FEAT: feat
          LABEL_FIX: fix
