name: github

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - opened
      - reopened

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3
      - run: .github/matchers.sh
      - name: gh
        uses: docker://ghcr.io/whilp/gh:latest@sha256:249ea1483755b7f917b06da56e51251ed36baf1ae093e86239af83fdee1dffbf
        env:
          CONTEXT: lint / github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_DEPENDENCIES: dependencies
          LABEL_FEAT: feat
          LABEL_FIX: fix
