name: github

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - reopened

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: gh
        uses: docker://ghcr.io/whilp/gh:latest@sha256:f37db63b4c916ee8a321eccd60c4700aedf91e2dc58c63cf1276709d1bb85603
        env:
          COMMAND: check-pr
          CONTEXT: lint / github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_DEPENDENCIES: dependencies
          LABEL_FEAT: feat
          LABEL_FIX: fix
