name: github

on:
  pull_request:
    types:
      - synchronize
      - labeled
      - unlabeled
      - reopened

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: gh
        uses: docker://ghcr.io/whilp/gh:latest@sha256:f53dfab9e95f4c922aad90d6b1271ba32159173a832003a695713e6a9a6a9798
        env:
          CONTEXT: lint / github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_DEPENDENCIES: dependencies
          LABEL_FEAT: feat
          LABEL_FIX: fix
