name: lint

on: [push]

jobs:
  buildifier:
    runs-on: ubuntu-18.04
    if: ${{! github.event.pull_request.merged}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: docker://whilp/buildifier:latest
        with:
          args: -lint=fix -mode=fix -r -v /github/workspace

      - name: check
        run: git diff --exit-code
