name: lint

on:
  push:
    branches-ignore:
      - master

jobs:
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: buildifier
        uses: docker://whilp/linter:latest@sha256:12357fbb9cd5aad09c2d397f301a7624fa12d5d437bd9dbf567d3e075f7845aa
        with:
          args: /buildifier -lint=fix -mode=fix -r -v .
      - name: check
        run: git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: shfmt
        uses: docker://whilp/linter:latest@sha256:12357fbb9cd5aad09c2d397f301a7624fa12d5d437bd9dbf567d3e075f7845aa
        with:
          args: /shfmt -l -w -i 2 .
      - name: check
        run: git diff --exit-code
