name: lint

on:
  push:
    branches-ignore:
      - main

jobs:
  # Can't use a matrix here because `uses` doesn't accept expressions.
  # https://github.community/t/expressions-in-docker-uri/16271
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/buildifier:latest@sha256:488dbdd5cd951198a1876f2005a7f291745c574b46d2e12916981f0b49bb9494
      - run: git diff --exit-code

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/black:latest@sha256:2a383a172fa80f822a8fa9666062f905e43f1a2496757a76b30215079f9b4a86
      - run: git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/shfmt:latest@sha256:6c97f3cf967233941067a7b25c3b9461d6e82d098ead5017659c4844823025bb
      - run: git diff --exit-code

  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/prettier:latest@sha256:c5a87e595bcdd2181467fa273110d69ead3829e56a446118b730491610c7f875
      - run: git diff --exit-code

  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/eslint:latest@sha256:3c82dd8161a4cc88ed43662704760f7b45735e455952150e7d86608271648e48
      - run: git diff --exit-code

  golangci-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/golangci-lint:latest@sha256:07ebab260c3b001af52dafd0843cf01655c555f30af383a6801261218eb5ae44
      - run: git diff --exit-code
