name: lint

on:
  push:
    branches-ignore:
      - main

jobs:
  # Can't use a matrix here because `uses` doesn't accept expressions.
  # https://github.community/t/expressions-in-docker-uri/16271
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/buildifier:latest@sha256:de11a82a3b934db3fc977e906fcd89a8781baac4226bf5bf9111be3c1dcb812a
      - run: git diff --exit-code

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/black:latest@sha256:0db2a634bd14f599295c1920c69c3baba74b3ed83252f1ea31e1e9b351185389
      - run: git diff --exit-code

  bandit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/bandit:latest@sha256:d0d3adc7149b702e97e010bd8ed57fe7b7646b37afc4300d46bab57c24aaabc4
      - run: git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/shfmt:latest@sha256:73dceeeed4a3454139ef245789917862b67cfb6aca716ce04ba23a9c8d3d3ddd
      - run: git diff --exit-code

  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/prettier:latest@sha256:4d7174c403ef0b7b6634ac63352cf8e29cafa5a0861b1d0c9f1076758982f7e5
      - run: git diff --exit-code

  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/eslint:latest@sha256:e5940581c8009bb8df83dc328fd212ffe0eee6b6e4b605a1107cc9df85026c5b
      - run: git diff --exit-code

  golangci-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: clean up
        run: rm -rf cmd/tools
      - name: lint
        uses: docker://ghcr.io/whilp/golangci-lint:latest@sha256:c2779a21a73fffe07d6b19f9e78d76f987b6a205c2f0afaf21c919812b0b956f
      - name: restore
        run: git checkout cmd/tools
      - run: git diff --exit-code
