name: lint

on:
  push:
    branches-ignore:
      - main

jobs:
  # Can't use a matrix here because `uses` doesn't accept expressions.
  # https://github.community/t/expressions-in-docker-uri/16271
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/buildifier:latest@sha256:67da91fdddd40e9947153bc9157ab9103c141fcabcdbf646f040ba7a763bc531
      - run: git diff --exit-code

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/black:latest@sha256:5509da74b6ce636b87247180032709d030dbbfbaf3eba635bf8b12a9481e043e
      - run: git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/shfmt:latest@sha256:6c97f3cf967233941067a7b25c3b9461d6e82d098ead5017659c4844823025bb
      - run: git diff --exit-code

  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/prettier:latest@sha256:9ecaec4d23e25f273cbf211e51e6e483aed9387892f9b04a5f7342b984ff2c47
      - run: git diff --exit-code

  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/eslint:latest@sha256:310ad6864c392b04eec79f65e1065b436dcb6b469c0c7be3bdba1b4ccfbb2664
      - run: git diff --exit-code

  golangci-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/golangci-lint:latest@sha256:1ea60bac591db7392a370d94c4873698ee87189f2c1de376bec0ae46a133dc45
      - run: git diff --exit-code
