name: lint

on:
  push:
    branches-ignore:
      - main

jobs:
  # Can't use a matrix here because `uses` doesn't accept expressions.
  # https://github.community/t/expressions-in-docker-uri/16271
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/buildifier:latest@sha256:81111cdb805e786f89dbd956148794f63c49b750f9f3937467b99150da317984
      - run: git add -N . && git diff --exit-code

  gazelle:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/gazelle:latest@sha256:8b4eb9b593a549284dbd507d92f63b4b480fc7ba321ef357b96120b9074456bb
      - run: git add -N . && git add -N . && git diff --exit-code

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/black:latest@sha256:56692cabf0f0d07aa3abe39f9f9a045984a4eb91e2e2ac84727b93fd6efc083f
      - run: git add -N . && git diff --exit-code

  bandit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/bandit:latest@sha256:a769abcc8e0996f3a220cd54265f6c23f178477f6a653aee4b0eb26b6f747f13
      - run: git add -N . && git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/shfmt:latest@sha256:5710cae31152a0900783936efa655443dacdb8a026db87c1896e02402762e289
      - run: git add -N . && git diff --exit-code

  shellcheck:
    runs-on: ubuntu-18.04
    env:
      MANIFEST: .git/ls-files.txt
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: Prep
        run: git ls-files -z > "${MANIFEST}"
      - name: lint
        uses: docker://ghcr.io/whilp/shellcheck:latest@sha256:a49f960a52b8f99d6ac0a5a5a72cedc4e7b1a367d2af02f4bb294b6f0cb4666e
      - run: git add -N . && git diff --exit-code

  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/prettier:latest@sha256:81a15d2c3ddbe0bf0b3cd7d1c07165dbf430c13d3bff760255a26d95717ebcd6
      - run: git add -N . && git diff --exit-code

  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/eslint:latest@sha256:e48222b2e26ccd34a5cfd820c735bf09ecd76dab72e7fe3a28adbb6e64f2b65b
      - run: git add -N . && git diff --exit-code

  golangci-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: clean up
        run: rm -rf cmd/tools
      - name: lint
        uses: docker://ghcr.io/whilp/golangci-lint:latest@sha256:bcaf5982263f72c4ed8594dcd28c14e1fce03cef03b0204e7ed2eb78626a65f9
      - name: restore
        run: git checkout cmd/tools
      - run: git add -N . && git diff --exit-code

  pyright:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/pyright:latest@sha256:688b6c15f1f995baa39d5e67bfdb43cf48326d55763456898b9f85e27806c4e0
      - run: git add -N . && git diff --exit-code
