name: lint

on:
  push:
    branches-ignore:
      - main

jobs:
  # Can't use a matrix here because `uses` doesn't accept expressions.
  # https://github.community/t/expressions-in-docker-uri/16271
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/buildifier:latest@sha256:500fd3fd6c4b79f6995341a40f034bf4e4896d543a88173e2817d2ff462b3db5
      - run: git diff --exit-code

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/black:latest@sha256:b00d2c66694310708337468a46a6d5e2cadfe433fd9d7b1afdba2f4e2a28e199
      - run: git diff --exit-code

  bandit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/bandit:latest@sha256:60a9e0deed87833eea24495e15409931da9a9826eda078f1d4bb11182ada002a
      - run: git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/shfmt:latest@sha256:b0b0ea60661140ff3b35da9b23ff9af51eb58db4f31daddaf8174e677dbc2825
      - run: git diff --exit-code

  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/prettier:latest@sha256:a5d5289413f05933657ab7bdffa36046ae594792d01479b6c637358d4841cbac
      - run: git diff --exit-code

  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/eslint:latest@sha256:070960fc87c61374eeaaf4fb5adfdec5d5f09d798cb74368aba40c5c78a91372
      - run: git diff --exit-code

  golangci-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: clean up
        run: rm -rf cmd/tools
      - name: lint
        uses: docker://ghcr.io/whilp/golangci-lint:latest@sha256:31cb70806a00fc40b2885dee516b5060e5273c46fc881f618b3e1ab2f6e6315d
      - name: restore
        run: git checkout cmd/tools
      - run: git diff --exit-code
