name: lint

on:
  push:
    branches-ignore:
      - main

jobs:
  # Can't use a matrix here because `uses` doesn't accept expressions.
  # https://github.community/t/expressions-in-docker-uri/16271
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/buildifier:latest@sha256:81111cdb805e786f89dbd956148794f63c49b750f9f3937467b99150da317984
      - run: git add -N . && git diff --exit-code

  gazelle:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/gazelle:latest@sha256:8b4eb9b593a549284dbd507d92f63b4b480fc7ba321ef357b96120b9074456bb
      - run: git add -N . && git add -N . && git diff --exit-code

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/black:latest@sha256:9118cc9ab7f4af4de1ce80212b70999d8d97cd0d746ccf8c7a27a8c7d1842e0e
      - run: git add -N . && git diff --exit-code

  bandit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/bandit:latest@sha256:709bdf25bc2c35d1815f2a3b14273bffa468b6bec2e70300db03e82440997269
      - run: git add -N . && git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/shfmt:latest@sha256:de328a0fae9a8bdf16a52c91b6afac995b660e354c54189c420e594276d19a38
      - run: git add -N . && git diff --exit-code

  shellcheck:
    runs-on: ubuntu-18.04
    env:
      MANIFEST: .git/ls-files.txt
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: Prep
        run: git ls-files -z > "${MANIFEST}"
      - name: lint
        uses: docker://ghcr.io/whilp/shellcheck:latest@sha256:a49f960a52b8f99d6ac0a5a5a72cedc4e7b1a367d2af02f4bb294b6f0cb4666e
      - run: git add -N . && git diff --exit-code

  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/prettier:latest@sha256:0b273429e4c14d498f4f21ede3236a7f3e30514b863c67d5672417fc46a62ee9
      - run: git add -N . && git diff --exit-code

  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/eslint:latest@sha256:e48222b2e26ccd34a5cfd820c735bf09ecd76dab72e7fe3a28adbb6e64f2b65b
      - run: git add -N . && git diff --exit-code

  golangci-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: clean up
        run: rm -rf cmd/tools
      - name: lint
        uses: docker://ghcr.io/whilp/golangci-lint:latest@sha256:b01544c6d601259ffcf4909fe280cdb03db53177f819b4e7421b23cd363f640d
      - name: restore
        run: git checkout cmd/tools
      - run: git add -N . && git diff --exit-code

  pyright:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: lint
        uses: docker://ghcr.io/whilp/pyright:latest@sha256:9df6a4ed08f7d78d8b7ddec627f9ef3af0f0b5b790dbac759bc2745e6326b4a3
      - run: git add -N . && git diff --exit-code
