name: lint

on:
  push:
    branches-ignore:
      - main

jobs:
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/buildifier:latest@sha256:488dbdd5cd951198a1876f2005a7f291745c574b46d2e12916981f0b49bb9494
      - name: check
        run: git diff --exit-code

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/black:latest@sha256:2a383a172fa80f822a8fa9666062f905e43f1a2496757a76b30215079f9b4a86
      - name: check
        run: git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/shfmt:latest@sha256:90b0297cfeb3b93a8fb5b0ed0a2e5e228d2a97dccee6b0f381796040ed34afcd
      - name: check
        run: git diff --exit-code

  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/prettier:latest@sha256:c63d0f9272803e07b7b05ed220802ab65a4df77d787a35a71152f535157929ae
      - name: check
        run: git diff --exit-code

  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/eslint:latest@sha256:9346f2a6bf0e9f8eae3505520beb1127e49818ad5b210bb9eb506a8df1469ef0
      - name: check
        run: git diff --exit-code
