name: lint

on:
  push:
    branches-ignore:
      - master

jobs:
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/buildifier:latest
      - name: check
        run: git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/shfmt:latest
      - name: check
        run: git diff --exit-code

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/black:latest
      - name: check
        run: git diff --exit-code
