name: lint

on:
  push:
    branches-ignore:
      - main

jobs:
  # Can't use a matrix here because `uses` doesn't accept expressions.
  # https://github.community/t/expressions-in-docker-uri/16271
  buildifier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/buildifier:latest@sha256:740f8b6c19908614b3a8846e442d2671b6ebeaf2759fc1af0786bf3e0b038083
      - run: git diff --exit-code

  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/black:latest@sha256:a3e2b95401c85411c1ad78594ddb1618c4f8b9c19aeff82e5ec3633f4766d288
      - run: git diff --exit-code

  shfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/shfmt:latest@sha256:6c97f3cf967233941067a7b25c3b9461d6e82d098ead5017659c4844823025bb
      - run: git diff --exit-code

  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/prettier:latest@sha256:65a016d2d260fd5b9e0476e90cc2b2870d2ab3c958d58ca57ebe6368243d42f5
      - run: git diff --exit-code

  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/eslint:latest@sha256:88ae7f5c5f1bc9e75b172c4b55b8de49658a4642baba44fbfd70a647fcfefcb5
      - run: git diff --exit-code

  golangci-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: lint
        uses: docker://whilp/golangci-lint:latest@sha256:1ea60bac591db7392a370d94c4873698ee87189f2c1de376bec0ae46a133dc45
      - run: git diff --exit-code
