name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: gh
        uses: docker://ghcr.io/whilp/gh:latest@sha256:a7495ee6eb11ebdf9b2d8b295cbe3957e506cc066151e54d817ed4b3dead50eb
        env:
          COMMAND: update-release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
