name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: gh
        uses: docker://ghcr.io/whilp/gh:latest@sha256:4d9b9217a273262791f71f42b331dae126a5f9223c83fbb8012294c857404289
        env:
          COMMAND: update-release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
