name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: gh
        uses: docker://ghcr.io/whilp/gh:latest@sha256:31642530a166c72b468d45e953eaf708726661b93572b8d3916464520d88fc47
        env:
          COMMAND: update-release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
