name: push

on:
  push:
    branches:
      - master

jobs:
  push:
    strategy:
      matrix:
        image:
          - devcontainer
          - shfmt
          - black
          - buildifier
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: docker login
        run: echo "$DOCKER_TOKEN" | docker login --password-stdin --username "$DOCKER_USER"
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
      - name: bazel run image/${{ matrix.image }}:push
        run: ./tools/bazel run --config=ci image/${{ matrix.image }}:push
