name: push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push:
    strategy:
      matrix:
        image:
          - image/devcontainer
          - cmd/shfmt
          - cmd/black
          - cmd/buildifier
          - cmd/prettier
          - cmd/eslint
          - cmd/bot
          - cmd/gh
          - cmd/golangci-lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2.1.2
        with:
          python-version: "3.7"
      - run: .github/matchers.sh
      - name: docker login ghcr.io
        run: echo "$DOCKER_TOKEN" | docker login --password-stdin --username "$DOCKER_USER" ghcr.io
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
      - name: bazel run ${{ matrix.image }}:push
        run: ./tools/bazel run --config=ci ${{ matrix.image }}:push
