name: scan

on:
  workflow_dispatch:
  schedule:
    - cron: "18 6 * * *"

jobs:
  codeql:
    strategy:
      matrix:
        language:
          - javascript
          - python
          - go
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/analyze@v1

  anchore:
    strategy:
      matrix:
        image:
          - image/devcontainer
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.1.4
        with:
          python-version: "3.7"
      - run: .github/matchers.sh
      - name: bazel run ${{ matrix.image }}:image
        run: ./tools/bazel run --config=ci ${{ matrix.image }}:image
      - uses: anchore/scan-action@v2
        with:
          image-reference: bazel/${{ matrix.image }}:image
          fail-build: true
          include-app-packages: true
          acs-report-enable: true
          debug: true
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
