name: scan

on:
  workflow_dispatch:
  schedule:
    - cron: "18 6 * * *"

jobs:
  codeql:
    strategy:
      matrix:
        language:
          - javascript
          - python
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/analyze@v1
