name: test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2.1.2
        with:
          python-version: "3.7"
      - run: .github/matchers.sh
      - name: bazel test
        run: ./tools/bazel test --config=ci //...
