name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.1
        with:
          python-version: "3.7"
      - run: .github/matchers.sh
      - name: bazel test
        run: ./tools/bazel test --config=ci ${GITHUB_HEAD_REF:---config=fast} //...
