name: test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2.0.1
        with:
          python-version: "3.7"
      - name: bazel test
        run: ./tools/bazel test --config=ci //...
