name: update

on:
  push:
    paths:
      - renovate.js
  schedule:
    - cron: "19 3 * * *"

jobs:
  renovate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: renovate
        uses: docker://renovate/renovate:latest@sha256:eb4bc6080c57e7988bb6902bb9482e7f02c6d7addd55381d8132e4e85faf791d
        env:
          RENOVATE_REPOSITORIES: whilp/world
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_ONBOARDING: false
          RENOVATE_CONFIG_FILE: renovate.js
          RENOVATE_LOGLEVEL: debug
