name: update

on:
  push:
    paths:
      - renovate.js
  schedule:
    - cron: "19 */3 * * *"

jobs:
  renovate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: renovate
        uses: docker://renovate/renovate:latest@sha256:29d2579a1fff11771e6485beb3174b8ba22882b6f19b77703319e987588d5238
        env:
          RENOVATE_REPOSITORIES: whilp/world
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_ONBOARDING: false
          RENOVATE_CONFIG_FILE: renovate.js
          RENOVATE_LOGLEVEL: debug
