name: update

on:
  workflow_dispatch:
  push:
    paths:
      - renovate.js
  schedule:
    - cron: "19 */3 * * *"

jobs:
  renovate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v2.1.1
        with:
          python-version: "3.7"
      # Use appmode/app tokens.
      # https://github.com/renovatebot/renovate/issues/6371
      # https://github.com/renovatebot/renovate/pull/6454
      - name: renovate
        uses: docker://renovate/renovate:latest@sha256:76ed218e86213292c762c9f705d0d854919a0189a9707c0386c42752a7081a60
        env:
          RENOVATE_REPOSITORIES: whilp/world
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_ONBOARDING: false
          RENOVATE_CONFIG_FILE: renovate.js
          RENOVATE_LOGLEVEL: debug
          RENOVATE_TRUSTLEVEL: high
