name: update

on:
  workflow_dispatch:
  push:
    paths:
      - renovate.js
      - .github/workflows/update.yml
  schedule:
    - cron: "19 */3 * * *"

jobs:
  renovate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: .github/matchers.sh
      - name: renovate
        uses: docker://ghcr.io/whilp/renovate:latest@sha256:03d2774ab92fe506dc9e230fc3549fabe68d768646bf3e409cdaadf3acc4b27f
        env:
          # These variables are used by the shimmed entrypoint to convert
          # GitHub app credentials to a full-fledged access token suitable for
          # renovate's use.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_ID: ${{ secrets.BOT_ID }}
          APP_KEY: ${{ secrets.BOT_KEY }}

          # These variables are either processed by renovate itself or by the
          # build tools it invokes.
          GOCACHE: /tmp/go-build
          RENOVATE_REPOSITORIES: whilp/world
          RENOVATE_GITAUTHOR: "Renovate Bot <bot@renovate.com>"
          RENOVATE_USERNAME: renovatebot
          RENOVATE_ONBOARDING: false
          RENOVATE_CONFIG_FILE: renovate.js
          RENOVATE_LOGLEVEL: debug
          RENOVATE_TRUSTLEVEL: high
