name: update

on:
  push:
    paths:
      - renovate.js
  schedule:
    - cron: "19 */3 * * *"

jobs:
  renovate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: renovate
        uses: docker://renovate/renovate:latest@sha256:7da9198c3f97c7640ff0e85f513a040dd68277b555ba7cad6f56043afff2a966
        env:
          RENOVATE_REPOSITORIES: whilp/world
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_ONBOARDING: false
          RENOVATE_CONFIG_FILE: renovate.js
          RENOVATE_LOGLEVEL: debug
      - name: bazel versions
        run: ./tools/bazel run --config=ci versions $PWD/versions/versions.bzl
      - run: git push
