name: update

on:
  push:
    paths:
      - renovate.js
  schedule:
    - cron: "19 */3 * * *"

jobs:
  renovate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 2
      - name: renovate
        uses: docker://renovate/renovate:latest@sha256:a852e4ee0aa298ab3fec475dd21965204badddc474e414df60a7e6d17fb8fcbf
        env:
          RENOVATE_REPOSITORIES: whilp/world
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_ONBOARDING: false
          RENOVATE_CONFIG_FILE: renovate.js
          RENOVATE_LOGLEVEL: debug
