name: update

on:
  workflow_dispatch:
  push:
    paths:
      - renovate.js
      - .github/workflows/update.yml
  schedule:
    - cron: "19 */3 * * *"

jobs:
  renovate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-python@v2.1.2
        with:
          python-version: "3.7"
      - run: .github/matchers.sh
      - uses: ./cmd/bot
        id: bot
        with:
          bot-id: ${{ secrets.BOT_ID }}
          bot-key: ${{ secrets.BOT_KEY }}
          bot-installation-id: ${{ secrets.BOT_INSTALLATION_ID }}
          bot-client-id: ${{ secrets.BOT_CLIENT_ID }}
          bot-client-secret: ${{ secrets.BOT_CLIENT_SECRET }}
      - name: Prep
        run: |
          mkdir ~/.cache
          chmod o+w ~/.cache
      - name: renovate
        uses: docker://renovate/renovate:latest@sha256:0594765cae2d3939fe0d3c89a63086c804efc8b7643ec5297e927fe0b8657c62
        env:
          RENOVATE_REPOSITORIES: whilp/world
          RENOVATE_GITAUTHOR: "Renovate Bot <bot@renovate.com>"
          RENOVATE_USERNAME: renovatebot
          # https://github.com/renovatebot/renovate/blob/a2b267137005458eca16a39482da458e2ee4e819/lib/util/http/auth.ts#L20
          RENOVATE_TOKEN: x-access-token:${{ steps.bot.outputs.token }}
          RENOVATE_ONBOARDING: false
          RENOVATE_CONFIG_FILE: renovate.js
          RENOVATE_LOGLEVEL: debug
          RENOVATE_TRUSTLEVEL: high
